site_name: C2 Language Documentation
repo_url: https://github.com/c2lang
theme: readthedocs
extra_css:
  - css/highlight.css
extra_javascript:
  - js/highlight.pack.js
pages:
- Introduction:
  - Philosophy: index.md
  - introduction/evolution.md
  - Hello World: introduction/helloworld.md
  - introduction/code_fragments.md
  - Changes from C: introduction/changes_from_c.md
- Getting Started:
  - getting_started/installation.md
  - getting_started/my_first_project.md
- C2 Language:
  - language/formatting.md
  - language/naming.md
  - language/keywords.md
  - language/basic_types.md
  - User-defined types: language/user_types.md
  - language/variables.md
  - language/functions.md
  - language/modules.md
  - language/attributes.md
  - language/bit_offsets.md
  - language/struct_functions.md
  - language/operators.md
  - language/builtin_functions.md
- Build system:
  - build_system/intro.md
  - build_system/recipe_file.md
  - build_system/build_file.md
  - Export Control: build_system/symbols.md
  - C2 Module: build_system/c2module.md
  - External Libraries: build_system/libraries.md
  - build_system/diagnostics.md
- Development:
  - development/contributing.md
  - development/internals.md
  - development/automated_tests.md
  - development/current_status.md
